site_name: IIT Motorsports Docs
site_author: 'Noah Husby'
docs_dir: docs/
repo_name: 'illinois-tech-motorsports/docs'
repo_url: 'https://github.com/illinois-tech-motorsports/docs'
nav:
    - Home: index.md
theme:
  name: 'material'
